export interface RolePreset {
  name: string;
  roleKey: string;
  description: string;
  icon: string;
  modules: string[];
}

export const ROLE_PRESETS: Record<string, RolePreset> = {
  'Super Admin': {
    name: 'Super Admin / Owner',
    roleKey: 'Super Admin',
    description: 'Full unrestricted system access to all business modules, operations launchpad, financial data, and controls.',
    icon: '👑',
    modules: [
      'dashboards',
      '/',
      'dashboard',
      '/dashboard',
      '/Dashboard/Salesman',
      '/Dashboard/Warehouse',
      'crm',
      '/crm/leads',
      '/crm/quotations',
      '/Sales/Customers/List',
      '/Sales/Customers/Add',
      '/Customers/list',
      '/Sales/Salesman/List',
      '/Sales/Salesman/Add',
      '/Salesman/list',
      '/crm/due-list',
      '/crm/follow-ups',
      '/crm/recovery-history',
      'sales',
      '/Sales/Invoice/List',
      '/sales/invoice/list',
      '/Sales/Invoice/New',
      '/sales/orders',
      '/sales/price-lists',
      '/Sales/Delivery-Challan/List',
      '/Delivery-Challan/List',
      '/Sales/Delivery-Challan/Add',
      '/Sales/Shop-Dispatch/List',
      '/Sales/Sales-Return/List',
      '/sales/sales-return/list',
      '/Sales/Sales-Return/Add',
      '/Sales-Return/Debit-Notes/List',
      '/Sales/Sales-Return-Receipt/List',
      '/sales/sales-return-receipt/list',
      '/Registration/InvoiceReceipt/List',
      '/Sales/InvoiceReceipt/List',
      'purchase',
      '/Purchase/Purchases/List',
      '/Purchase/Purchases/Add',
      '/purchase/orders',
      '/purchase/quotations',
      '/Purchase/GRN/List',
      '/Purchase/GRN/Add',
      '/Purchase/Inward-Challan/List',
      '/Purchase/Shop-Receiving',
      '/Purchase/Purchase-Return/List',
      '/Purchase/Purchase-Return-Receipt/List',
      '/Purchase/Purchase-Receipt/List',
      '/purchase/vendor-ledger',
      '/Purchase/Vendor/List',
      '/Purchase/Vendor/Add',
      'pos',
      '/pos/terminal',
      '/pos/register',
      '/pos/hold-orders',
      '/pos/barcode-generator',
      'inventory',
      '/inventory/warehouse-terminal',
      '/Administration/Products/List',
      '/Administration/Products/Bulk-Upload',
      '/Administration/StockTransfer/List',
      '/Administration/StockTransfer/Add',
      '/inventory/stock-adjustments',
      '/inventory/stock-audits',
      '/inventory/adjustment-types',
      '/inventory/stock-ledger',
      '/inventory/scheduled-valuations',
      '/Warehouse/Return-Challan',
      '/Warehouse/Shop-Return',
      'accounts',
      'registration',
      '/Registration/Chart-of-Account/List',
      '/Registration/Chart-of-Account/Add',
      '/Registration/Vouchers/List',
      '/Registration/Vouchers/Add',
      '/registration/journal-vouchers',
      '/Registration/Bank-Account/BankAccountList',
      '/Registration/Bank-Account/Add',
      '/registration/bank-reconciliation',
      '/registration/trial-balance',
      '/Registration/Multi-Invoice-Receipt/Add',
      '/Inventory/OpeningStock/List',
      'classification',
      'administration',
      '/Administration/Categories/List',
      '/administration/subcategories',
      '/Administration/Surface-Finish',
      '/Administration/Brands',
      '/administration/tile-dimensions',
      '/Administration/UOM/List',
      '/Administration/Locations/List',
      '/Administration/Locations/Add',
      '/Administration/Transportation/List',
      '/Administration/Transportation/Add',
      '/administration/drivers',
      '/company',
      'reports',
      '/Reports/Reports-Dashboard',
      '/Reports/Stock-Report',
      '/Reports/Sales-Report',
      '/Reports/Purchase-Report',
      '/Reports/Account-Report',
      '/Reports/Holding-Report',
      '/Reports/Balance-Sheet',
      'hr',
      'human resource',
      'human resources',
      '/Human-Resources/Employees',
      '/Human-Resources/Employees/Add',
      '/Human-Resources/Attendance',
      '/Human-Resources/Salary-Sheet',
      '/Human-Resources/Salary-Structure',
      '/Human-Resources/Pay-Heads',
      '/Human-Resources/Leaves',
      '/Human-Resources/Loans',
    ],
  },
  'Salesman': {
    name: 'Sales Executive / Salesman',
    roleKey: 'Salesman',
    description: 'Field & showroom sales: Home, CRM leads & inquiries, orders, invoices, customer receipts, and dues.',
    icon: '🛒',
    modules: [
      'dashboards',
      '/',
      'dashboard',
      '/dashboard',
      '/Dashboard/Salesman',
      'crm',
      '/crm/leads',
      '/crm/quotations',
      '/Sales/Customers/List',
      '/crm/due-list',
      '/crm/follow-ups',
      '/crm/recovery-history',
      'sales',
      '/Sales/Invoice/List',
      '/sales/orders',
      '/sales/price-lists',
      '/Sales/Delivery-Challan/List',
      '/Sales/Shop-Dispatch/List',
      '/Sales/Sales-Return/List',
      '/Sales-Return/Debit-Notes/List',
      '/Sales/Sales-Return-Receipt/List',
      '/Registration/InvoiceReceipt/List',
      '/Sales/InvoiceReceipt/List',
      'reports',
      '/Reports/Sales-Report',
    ],
  },
  'Warehouse Manager': {
    name: 'Warehouse & Inventory Manager',
    roleKey: 'Warehouse Manager',
    description: 'Manages physical warehouse operations, terminal, stock movements, adjustments, audits, and logistics queues.',
    icon: '📦',
    modules: [
      'dashboards',
      '/',
      'dashboard',
      '/dashboard',
      '/Dashboard/Warehouse',
      'inventory',
      '/inventory/warehouse-terminal',
      '/Administration/Products/List',
      '/Administration/Products/Bulk-Upload',
      '/Administration/StockTransfer/List',
      '/inventory/stock-adjustments',
      '/inventory/stock-audits',
      '/inventory/adjustment-types',
      '/inventory/stock-ledger',
      '/inventory/scheduled-valuations',
      '/Warehouse/Return-Challan',
      '/Warehouse/Shop-Return',
      'sales',
      '/Sales/Delivery-Challan/List',
      '/Sales/Shop-Dispatch/List',
      'purchase',
      '/Purchase/Inward-Challan/List',
      '/Purchase/Shop-Receiving',
      '/Purchase/GRN/List',
      'classification',
      '/Administration/Categories/List',
      '/administration/subcategories',
      '/Administration/Surface-Finish',
      '/Administration/UOM/List',
      '/Administration/Locations/List',
      '/Administration/Transportation/List',
      '/administration/drivers',
      '/Inventory/OpeningStock/List',
      'reports',
      '/Reports/Stock-Report',
      '/Reports/Holding-Report',
    ],
  },
  'Accountant': {
    name: 'Finance & Accounts Officer',
    roleKey: 'Accountant',
    description: 'Financial ledger, vouchers, trial balance, bank reconciliation, receivable/payable receipts, and balance sheets.',
    icon: '📊',
    modules: [
      'dashboards',
      '/',
      'dashboard',
      '/dashboard',
      'accounts',
      'registration',
      '/Registration/Chart-of-Account/List',
      '/Registration/Vouchers/List',
      '/registration/journal-vouchers',
      '/Registration/Bank-Account/BankAccountList',
      '/registration/bank-reconciliation',
      '/registration/trial-balance',
      '/Registration/Multi-Invoice-Receipt/Add',
      '/Inventory/OpeningStock/List',
      'sales',
      '/Registration/InvoiceReceipt/List',
      '/Sales/InvoiceReceipt/List',
      '/Sales/Sales-Return-Receipt/List',
      'purchase',
      '/Purchase/Purchase-Receipt/List',
      '/Purchase/Purchase-Return-Receipt/List',
      '/purchase/vendor-ledger',
      'crm',
      '/crm/due-list',
      '/crm/recovery-history',
      'reports',
      '/Reports/Reports-Dashboard',
      '/Reports/Account-Report',
      '/Reports/Holding-Report',
      '/Reports/Balance-Sheet',
      '/Reports/Sales-Report',
      '/Reports/Purchase-Report',
    ],
  },
  'POS Cashier': {
    name: 'POS Cashier / Counter Operator',
    roleKey: 'POS Cashier',
    description: 'Front-desk point of sale, barcode scanning, shift register, instant counter billing, and held orders.',
    icon: '💳',
    modules: [
      'dashboards',
      '/',
      'pos',
      '/pos/terminal',
      '/pos/register',
      '/pos/hold-orders',
      '/pos/barcode-generator',
      'sales',
      '/Sales/Invoice/List',
      '/Registration/InvoiceReceipt/List',
      '/Sales/Sales-Return/List',
      '/Sales/Customers/List',
    ],
  },
  'HR Manager': {
    name: 'Human Resources & Payroll Manager',
    roleKey: 'HR Manager',
    description: 'Staff directory, biometric attendance sheets, salary payroll generation, leave requests, and loans.',
    icon: '👥',
    modules: [
      'dashboards',
      '/',
      'hr',
      'human resource',
      'human resources',
      '/Human-Resources/Employees',
      '/Human-Resources/Attendance',
      '/Human-Resources/Salary-Sheet',
      '/Human-Resources/Salary-Structure',
      '/Human-Resources/Pay-Heads',
      '/Human-Resources/Leaves',
      '/Human-Resources/Loans',
    ],
  },
};

export const getModulesForRole = (role: string): string[] => {
  const preset = ROLE_PRESETS[role];
  if (preset) return preset.modules;
  if (role && role.toLowerCase().includes('admin')) {
    return ROLE_PRESETS['Super Admin'].modules;
  }
  return ROLE_PRESETS['Super Admin'].modules;
};
